package high.mackenzie.autumn.resources;

import java.lang.annotation.Retention;
import java.lang.annotation.RetentionPolicy;

/**
 * This type of annotation to indicate that a part of the compiler is ready for release.
 *
 * <p>
 * This annotation is usually not applied to autogenerated code.
 * </p>
 *
 * @author Mackenzie High
 */
@Retention(RetentionPolicy.SOURCE)
public @interface Finished
{
    /**
     * This is the date YYYY/MM/DD on which the piece was declared finished.
     */
    public String value();
}
